# Generated by Django 6.0 on 2025-12-23 06:34

import api.utils
import user_auth.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('picture', models.ImageField(null=True, upload_to=api.utils.rename_upload, verbose_name='Profile picture')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('company', 'Company'), ('admin', 'Admin'), ('support', 'Support'), ('developer', 'Developer')], max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('password_changed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user_auth.managers.MissionUserManager()),
            ],
        ),
    ]
