# Generated by Django 6.0 on 2025-12-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
