# Generated by Django 6.0 on 2025-12-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_missionuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionuser',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
