# Generated by Django 6.0 on 2025-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_missionuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionuser',
            name='picture',
            field=models.ImageField(upload_to='media/', verbose_name='Profile picture'),
        ),
    ]
