# Generated by Django 6.0 on 2025-12-18 06:41

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_missionuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionuser',
            name='picture',
            field=models.ImageField(null=True, upload_to=api.utils.rename_upload, verbose_name='Profile picture'),
        ),
    ]
