# Generated by Django 6.0 on 2025-12-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_missionuser_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='missionuser',
            managers=[
            ],
        ),
    ]
