# Generated by Django 6.0 on 2025-12-18 06:44

import user_auth.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_missionuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='missionuser',
            managers=[
                ('objects', user_auth.managers.MissionUserManager()),
            ],
        ),
    ]
