# Generated by Django 6.0 on 2025-12-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_missionuser_groups_missionuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='missionuser',
            name='user_permissions',
        ),
    ]
