# Generated by Django 6.0 on 2025-12-17 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission_admin', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_rate', models.FloatField(default=0.0)),
                ('test_rate', models.FloatField(default=0.0)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrappers', to='mission_admin.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('file', models.FileField(upload_to='tests/')),
                ('rate', models.FloatField(default=0.0)),
                ('ended', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='student.skillwrapper')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('Rookie', 'Rookie'), ('Apprentice', 'Apprentice'), ('Intermediate', 'Intermediate'), ('Challenger', 'Challenger'), ('Expert', 'Expert'), ('Master', 'Master'), ('Senior', 'Senior')], default='Rookie', max_length=100)),
                ('global_rate', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='user_auth.missionuser')),
            ],
        ),
        migrations.AddField(
            model_name='skillwrapper',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='student.student'),
        ),
        migrations.CreateModel(
            name='StudentKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document_url', models.TextField()),
                ('status', models.CharField(choices=[('not-validated', 'Not validated'), ('in_progress', 'In progress'), ('validated', 'Validated')], default='in_progress', max_length=90)),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kycs', to='student.student')),
            ],
        ),
    ]
