# Generated by Django 6.0 on 2025-12-21 22:14

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentkyc',
            name='document_url',
        ),
        migrations.AddField(
            model_name='studentkyc',
            name='document',
            field=models.FileField(null=True, upload_to=api.utils.document_rename_upload),
        ),
    ]
