# Generated by Django 6.0 on 2025-12-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_type',
        ),
    ]
