# Generated by Django 6.0 on 2025-12-17 06:37

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('not-validated', 'Not validated')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='', verbose_name='Company picture')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document_url', models.TextField()),
                ('status', models.CharField(choices=[('not-validated', 'Not validated'), ('in_progress', 'In progress'), ('validated', 'Validated')], max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Mission name')),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('Rookie', 'Rookie'), ('Apprentice', 'Apprentice'), ('Intermediate', 'Intermediate'), ('Challenger', 'Challenger'), ('Expert', 'Expert'), ('Master', 'Master'), ('Senior', 'Senior')], max_length=50)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Skills')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=50)),
                ('render_link', models.TextField(verbose_name='Render Link')),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
