# Generated by Django 6.0 on 2025-12-23 06:34

import api.utils
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to=api.utils.rename_upload, verbose_name='Company picture')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document', models.FileField(default=None, null=True, upload_to=api.utils.document_rename_upload)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('not-validated', 'Not validated'), ('pending', 'Pending'), ('validated', 'Validated')], default='pending', max_length=90)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Mission name')),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('Rookie', 'Rookie'), ('Apprentice', 'Apprentice'), ('Intermediate', 'Intermediate'), ('Challenger', 'Challenger'), ('Expert', 'Expert'), ('Master', 'Master'), ('Senior', 'Senior')], max_length=50)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, verbose_name='Skills')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=50)),
                ('render_link', models.TextField(verbose_name='Render Link')),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('not-validated', 'Not validated')], default='pending', max_length=50)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='student.student', verbose_name='Related student')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='company.mission', verbose_name='Related mission')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rate', models.FloatField(default=0.0)),
                ('deadline_rate', models.FloatField(default=0.0)),
                ('communication_rate', models.FloatField(default=0.0)),
                ('rate', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='company.mission')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='student.student')),
            ],
        ),
    ]
