# Generated by Django 6.0 on 2025-12-17 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('student', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student', verbose_name='applications'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='user_auth.missionuser'),
        ),
        migrations.AddField(
            model_name='companykyc',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='company.company'),
        ),
        migrations.AddField(
            model_name='mission',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='company.company'),
        ),
        migrations.AddField(
            model_name='mission',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='student.student'),
        ),
        migrations.AddField(
            model_name='application',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.mission', verbose_name='applications'),
        ),
    ]
