# Generated by Django 6.0 on 2025-12-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('waiting_for_rate', 'Waiting for rate'), ('completed', 'Completed')], default='not_started', max_length=50),
        ),
    ]
