# Generated by Django 6.0 on 2025-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=models.ImageField(upload_to='media/', verbose_name='Company picture'),
        ),
    ]
