# Generated by Django 6.0 on 2025-12-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_mission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='deadline_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='quality_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
