# Generated by Django 6.0 on 2025-12-17 10:07

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=models.ImageField(upload_to=api.utils.rename_upload, verbose_name='Company picture'),
        ),
    ]
