# Generated by Django 6.0 on 2025-12-17 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_picture'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='student',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rate', models.FloatField(default=0.0)),
                ('deadline_rate', models.FloatField(default=0.0)),
                ('communication_rate', models.FloatField(default=0.0)),
                ('rate', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='company.mission')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='student.student')),
            ],
        ),
    ]
