# Generated by Django 6.0 on 2025-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_mission_student_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companykyc',
            name='document_url',
        ),
        migrations.AddField(
            model_name='companykyc',
            name='document',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='companykyc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
