# Generated by Django 6.0 on 2025-12-17 17:08

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_companykyc_document_url_companykyc_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companykyc',
            name='document',
            field=models.FileField(default=None, null=True, upload_to=api.utils.document_rename_upload),
        ),
    ]
