# Generated by Django 6.0 on 2025-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companykyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companykyc',
            name='status',
            field=models.CharField(choices=[('not-validated', 'Not validated'), ('pending', 'Pending'), ('validated', 'Validated')], default='pending', max_length=90),
        ),
    ]
