# Generated by Django 6.0 on 2025-12-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_companykyc_status'),
        ('student', '0002_remove_studentkyc_document_url_studentkyc_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='company.mission', verbose_name='applications'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='student.student', verbose_name='applications'),
        ),
    ]
